skip_clone: true

steps:
  deploy:
    image: alpine
    secrets: [ssh_private_key, server_ip, ssh_user, deploy_path, compose_file]
    commands:
      - apk add --no-cache openssh
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan -t rsa "$SERVER_IP" >> ~/.ssh/known_hosts
      - echo Deploying
      - ssh -i ~/.ssh/id_rsa $SSH_USER@$SERVER_IP "cd $DEPLOY_PATH && git pull origin main && sudo docker compose -f $COMPOSE_FILE up -d --build --wait"

  report:
    image: alpine
    secrets: [webhook]
    when:
      status: [failure]
    commands:
      - apk add --no-cache curl
      - curl -X POST -H "Content-type:\ application/json" --data "{\"embeds\":[{\"title\":\"Deploy Failed\",\"color\":16711680,\"url\":\"$CI_PIPELINE_URL\"}]}" $WEBHOOK
